//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveConsole.Properties.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom :.
        /// </summary>
        internal static string ask_name {
            get {
                return ResourceManager.GetString("ask_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le dossier/fichier source :.
        /// </summary>
        internal static string ask_sourcepath {
            get {
                return ResourceManager.GetString("ask_sourcepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le dossier de destination de la sauvegarde :.
        /// </summary>
        internal static string ask_targetpath {
            get {
                return ResourceManager.GetString("ask_targetpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez un type parmi la liste ci-dessous..
        /// </summary>
        internal static string ask_type {
            get {
                return ResourceManager.GetString("ask_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au revoir.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de supprimer une sauvegarde..
        /// </summary>
        internal static string choice_delete {
            get {
                return ResourceManager.GetString("choice_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi d&apos;exécuter toutes les sauvegardes..
        /// </summary>
        internal static string choice_runallsaves {
            get {
                return ResourceManager.GetString("choice_runallsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi d&apos;exécuter une sauvegarde..
        /// </summary>
        internal static string choice_runonesave {
            get {
                return ResourceManager.GetString("choice_runonesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de créer un sauvegarde..
        /// </summary>
        internal static string choice_save {
            get {
                return ResourceManager.GetString("choice_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Que voulez vous faire ? Choisissez parmi les choix ci-dessous..
        /// </summary>
        internal static string choose_action {
            get {
                return ResourceManager.GetString("choose_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une sauvegarde parmi la liste suivante..
        /// </summary>
        internal static string choose_save {
            get {
                return ResourceManager.GetString("choose_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé une sauvegarde.
        /// </summary>
        internal static string create_save {
            get {
                return ResourceManager.GetString("create_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez-vous la suppression de {0} ?.
        /// </summary>
        internal static string delete_comfirm {
            get {
                return ResourceManager.GetString("delete_comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde {0} a bien été supprimée..
        /// </summary>
        internal static string delete_end {
            get {
                return ResourceManager.GetString("delete_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une sauvegarde.
        /// </summary>
        internal static string delete_save {
            get {
                return ResourceManager.GetString("delete_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin {0} est introuvable. Vérifier votre sélection..
        /// </summary>
        internal static string exception_pathnotfound {
            get {
                return ResourceManager.GetString("exception_pathnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trop de sauvegardes ont été créés. Le maximum est {0}. Supprimez en une avant d&apos;en créer un nouvelle..
        /// </summary>
        internal static string exception_toomuchsaves {
            get {
                return ResourceManager.GetString("exception_toomuchsaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string language_en {
            get {
                return ResourceManager.GetString("language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string language_fr {
            get {
                return ResourceManager.GetString("language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue est bien passée en Français..
        /// </summary>
        internal static string language_ok {
            get {
                return ResourceManager.GetString("language_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir la langue parmis les choix ci-dessous..
        /// </summary>
        internal static string language_selection {
            get {
                return ResourceManager.GetString("language_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter toutes les sauvegardes.
        /// </summary>
        internal static string run_all_save {
            get {
                return ResourceManager.GetString("run_all_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter une sauvegarde.
        /// </summary>
        internal static string run_one_save {
            get {
                return ResourceManager.GetString("run_one_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde {0} crée..
        /// </summary>
        internal static string save_created {
            get {
                return ResourceManager.GetString("save_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde {0} exécutée avec succès..
        /// </summary>
        internal static string save_end {
            get {
                return ResourceManager.GetString("save_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde {0} est en cours..
        /// </summary>
        internal static string save_run {
            get {
                return ResourceManager.GetString("save_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel : Sauvegarde des fichiers différents..
        /// </summary>
        internal static string type_differential {
            get {
                return ResourceManager.GetString("type_differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total : Sauvegarde intégrale..
        /// </summary>
        internal static string type_total {
            get {
                return ResourceManager.GetString("type_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
